services:
  - type: web
    name: car-wash
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    pythonVersion: 3.11.9
    envVars:
      - key: DB_HOST
        value: your-remote-mysql-host
      - key: DB_USER
        value: your-db-username
      - key: DB_PASS
        value: your-db-password
      - key: DB_NAME
        value: car_detection
